### PR TITLE
ADD: Adding workflow for antivirus.

### PR DESCRIPTION
**Pull request by zssherman**
As part of the inititive to clean up the ARM-DOE repos, adding antivirus.yml action.

### CODE REVIEW

**Comment by zssherman** [comment]
@rcjackson Looks like the error is a dependency conflict from an older python 3.8

**Comment by zssherman** [comment]
No idea why things are failing now lol

**Comment by rcjackson** [comment]
It's failing to download mamba. I wonder if a server is down or something.

**Comment by zssherman** [comment]
@rcjackson Yeah i'm thinking that as well, will give it some time.

**Comment by zssherman** [comment]
@rcjackson I fix the builds etc, so this should now be good for a final review

**Pull request merged**
